version: "3"

services:
    backend:
        build:
            context: ./backend
        depends_on:
            - mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_username
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
            JWT_TOKEN_SECRET: "1Hl0w61DJIFEnhF1L7RzgOV"
        hostname: backend
        image: proyecto-final
        ports:
            - "3000:3000"
        volumes:
            - "./backend/app.js:/code/app.js"
            - "./backend/controllers:/code/controllers"
            - "./backend/models:/code/models"
            - "./backend/utils.js:/code/utils.js"
            - "./backend/package.json:/code/package.json"
            - "./backend/package-lock.json:/code/package-lock.json"
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_username
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
        hostname: mongo
        volumes:
            - "/mongo/db:/data/db"
        ports:
            - "27017:27017"
