version: "3"

services:
    backend:
        build:
            context: ./backend
        depends_on:
            - mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_username
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
            JWT_TOKEN_SECRET: "1Hl0w61DJIFEnhF1L7RzgOV"
        hostname: backend
        image: proyecto-final
        ports:
            - "3000:3000"
        volumes:
            - "./backend/app.js:/code/app.js"
            - "./backend/controllers:/code/controllers"
            - "./backend/models:/code/models"
            - "./backend/utils.js:/code/utils.js"
            - "./backend/package.json:/code/package.json"
            - "./backend/package-lock.json:/code/package-lock.json"
    # frontend:
    #     build:
    #         context: ./frontend
    #     depends_on:
    #         - backend
    #     hostname: frontend
    #     image: proyecto-final-frontend
    #     ports:
    #         - "5000:5000"
    #     volumes:
    #         - "./frontend/frontServer.js:/src/frontServer.js"
    #         - "./frontend/views:/src/views"
    #         # - "./backend/models:/code/models"
    #         - "./frontend/package.json:/src/package.json"
    #         - "./frontend/package-lock.json:/src/package-lock.json"
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_username
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
        hostname: mongo
        volumes:
            - "/mongo/db:/data/db"
        ports:
            - "27017:27017"
